import "./globals.css";
import { ReactNode } from "react";
import { OcidProvider } from "../contexts/OcidContext"; // 대소문자를 정확히 맞춰서 import
import Header from "@/nav/Header";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header/>
        <OcidProvider>
          {children}
        </OcidProvider>
      </body>
    </html>
  );
}