import "./globals.css";
import { ReactNode } from "react";
import { OcidProvider } from "../contexts/OcidContext"; // 대소문자를 정확히 맞춰서 import
import Header from "@/nav/Header";
import { CharacterStatProvider } from "@/contexts/CharacterStatContext";
import { CharacterInfoProvider } from "@/contexts/CharacterInfoContext";

export const metadata = {
  title: "메이플 캐릭터 정보 & 경험치 계산기",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <CharacterInfoProvider>
          <CharacterStatProvider>
            <OcidProvider>{children}</OcidProvider>
          </CharacterStatProvider>
        </CharacterInfoProvider>
      </body>
    </html>
  );
}
